### ISSUE TITLE
Cannot read property 'siteinfo' of undefined

### ISSUE THREAD

**Issue by qarkai** [seeeeew/SteamGiftsHelper#25]
Extension stopped working with error
```
Error in event handler for (unknown): TypeError: Cannot read property 'siteinfo' of undefined
    at init (chrome-extension://aeolcjbaammbkgaiagooljfdepnjmkfd/includes/AutoPatchWork.js:98:28)
```
I believe it's due to some changes on site since other SteamGifts's extension doesn't work too with similar error.

**Comment by qarkai** [comment]
Oops, sorry, that's not SteamGiftsHelper's error. Nevertheless it doesn't work for me even if I disable AutoPatchWork and adblocking extensions.

**Comment by seeeeew** [comment]
Did you install SteamGiftsHelper for the first time or have you used it before and it stopped working? If you just installed it, deactivate and then reactivate all of SteamGiftHelpers features. (This is a known bug, see #20.)

**Comment by qarkai** [comment]
Thanks, de- and reactivating features helped. Why this workaround is not in extension's description on  Chrome Web Store?

**Comment by seeeeew** [comment]
I wanted to fix the bug immediately, but then I got distracted and forgot about it. I'll probably either fix the bug or update the description on the weekend.

**Comment by qarkai** [comment]
Anyway thanks for this extension :)

**Comment by seeeeew** [comment]
Thanks for trying it out and giving it another chance after it initially didn't work. :D
